name: Test Streamlit App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Set environment variables
        run: |
          echo "EXPERIENCES_URL=${{ secrets.EXPERIENCES_URL }}" >> $GITHUB_ENV
          echo "SKILLS_URL=${{ secrets.SKILLS_URL }}" >> $GITHUB_ENV
          echo "PROJECTS_URL=${{ secrets.PROJECTS_URL }}" >> $GITHUB_ENV
          echo "CERTIFICATES_URL=${{ secrets.CERTIFICATES_URL }}" >> $GITHUB_ENV
          echo "IMAGE_URL=${{ secrets.IMAGE_URL }}" >> $GITHUB_ENV

      - name: Run Streamlit app (Debug)
        run: |
          source .venv/bin/activate
          streamlit run portfolio.py --server.headless=true
